server:
    port: 8083

spring:
    application:
        name: api-gateway
    zipkin:
        base-url: http://localhost:9411
    cloud:
       gateway:
          routes:
            - id: CUSTOMER-SERVICE
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/v1/customers/**
            - id: products
              uri: lb://PRODUCT
              predicates:
                - Path=/api/v1/products/**
            - id: KEYCLOAK
              uri: http://localhost:8080
              predicates:
                - Path=/auth/**
            - id: MEDIA
              uri: lb://MEDIA
              predicates:
                - Path=/api/v1/media/**
            - id: ORDERS
              uri: lb://ORDERS
              predicates:
                - Path=/api/v1/orders/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true